# Generated by Django 3.1 on 2022-07-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=64)),
                ('courseSubject', models.CharField(choices=[('Math', 'Math'), ('Computer Science', 'Computer Science'), ('History', 'History'), ('English', 'English'), ('Science', 'Science')], max_length=64)),
                ('courseProfessor', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=64)),
                ('studentMajor', models.CharField(choices=[('Math', 'Math'), ('Computer Science', 'Computer Science'), ('History', 'History'), ('Undecided', 'Undecided'), ('English', 'English'), ('Science', 'Science')], max_length=64)),
                ('studentMinor', models.CharField(blank=True, choices=[('Math', 'Math'), ('Computer Science', 'Computer Science'), ('History', 'History'), ('Undecided', 'Undecided'), ('English', 'English'), ('Science', 'Science')], max_length=64)),
                ('studentCourses', models.ManyToManyField(related_name='students', to='myApp.Course')),
            ],
        ),
    ]
