# Generated by Django 3.1 on 2022-07-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseStudents',
            field=models.ManyToManyField(related_name='courses', to='myApp.Student'),
        ),
    ]
